language: node_js
node_js:
  - "14"
before_script:
  - cd 05-ionic-project
  - npm install
script: npm run build
deploy:
  local-dir: 05-ionic-project/www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
notifications:
  email: false
